In [7]:
import sys
sys.path.append('/data/users/cs20s037/CITNonLinear/scripts')
from nlcd_user import *

In [11]:
#Example data for nlcd_single function which takes only one trio 
L=np.random.binomial(1,0.5,300)
A=0.9*L+np.random.normal(0,1,300)
B=0.1*A+np.random.normal(0,1,300)

In [12]:

nlcd_single(L,A,B,shuffles=500,algo='KRR',verbose=True)

The final p value is  0.4900398406374502
Test 1 L assoc B  0.4342629482071713
Test 2 L assoc A | B  0.00199203187250996
Test 3 A assoc B | L  0.4900398406374502
Test 4 L ind B | A  0.39243027888446214
Overlap score from Test 4  0.289316475700653
Seed set at  4134368910613559029

[0.4900398406374502,
 0.4342629482071713,
 0.00199203187250996,
 0.4900398406374502,
 0.39243027888446214,
 0.289316475700653,
 4134368910613559029]

In [13]:
#reproduce the result
nlcd_single(L,A,B,shuffles=500,algo='KRR',sample_seed=4134368910613559029)

The final p value is  0.4900398406374502
Test 1 L assoc B  0.4342629482071713
Test 2 L assoc A | B  0.00199203187250996
Test 3 A assoc B | L  0.4900398406374502
Test 4 L ind B | A  0.39243027888446214
Overlap score from Test 4  0.289316475700653
Seed set at  4134368910613559029

[0.4900398406374502,
 0.4342629482071713,
 0.00199203187250996,
 0.4900398406374502,
 0.39243027888446214,
 0.289316475700653,
 4134368910613559029]

In [14]:
#example data for nlcd_group function where you can feed in multiple trios and get a dataframe as result 
#here it contains two trios 
#one independent and the other causal 
data=[]
for i in range(2):
    L=np.random.binomial(1,0.5,1000)
    A=0.1*L+np.random.normal(0,1,1000)
    if(i==0):
        B=0.5*L+np.random.normal(0,1,1000)
    if(i==1):
        B=0.5*A+np.random.normal(0,1,1000)
    data.append([L,A,B])

In [15]:
result=nlcd_batch(data,shuffles=50,algo='KRR',reverse=False,usercall=True)

Seed Set at  173139788072421203623186426139092738707
Algo  KRR  shuffles  50  datasize =  1000  reverse  False
start time:  1743794257.35316  end time:  1743794262.2322276 Execution time: 4.879067659378052 seconds

In [ ]:
result

,p_final,p_LassocB,p_LassocA|B,p_AassocB|L,p_LindB|A,OS Test 4,child_seed,parent_seed
0,0.615385,0.019231,0.115385,0.615385,0.423077,0.471299,1496583405831959912,173139788072421203623186426139092738707
1,0.538462,0.192308,0.269231,0.019231,0.538462,0.478935,3141462066089290613,same

In [17]:
result=nlcd_batch(data,shuffles=50,algo='KRR',sample_seed=173139788072421203623186426139092738707,usercall=True)

Seed Set at  173139788072421203623186426139092738707
Algo  KRR  shuffles  50  datasize =  1000  reverse  False
start time:  1743794312.3793907  end time:  1743794316.4504414 Execution time: 4.071050643920898 seconds

In [18]:
result

,p_final,p_LassocB,p_LassocA|B,p_AassocB|L,p_LindB|A,OS Test 4,child_seed,parent_seed
0,0.615385,0.019231,0.115385,0.615385,0.423077,0.471299,1496583405831959912,173139788072421203623186426139092738707
1,0.538462,0.192308,0.269231,0.019231,0.538462,0.478935,3141462066089290613,same

In [19]:
#can reproduce a specific trio result by looking at the child seed from the above
#example see the seed against the row number 1 for data[1] 
nlcd_single(np.array(data[1][0]),np.array(data[1][1]),np.array(data[1][2]),shuffles=50,algo='KRR',sample_seed=3141462066089290613,verbose=True)

The final p value is  0.5384615384615384
Test 1 L assoc B  0.19230769230769232
Test 2 L assoc A | B  0.2692307692307692
Test 3 A assoc B | L  0.019230769230769232
Test 4 L ind B | A  0.5384615384615384
Overlap score from Test 4  0.4789352921311164
Seed set at  3141462066089290613

[0.5384615384615384,
 0.19230769230769232,
 0.2692307692307692,
 0.019230769230769232,
 0.5384615384615384,
 0.4789352921311164,
 3141462066089290613]

## rebuttal changes

### horizontal pleiotropy

In [21]:
trio=read_data('/data/users/cs20s037/CITNonLinear/data/Linearpleio1000.txt')
L=trio[0][0]
A=trio[0][1]
B=trio[0][2]

In [18]:

nlcd_single(L,A,B,shuffles=500,algo='KRR',verbose=True)

The final p value is  0.13545816733067728
Test 1 L assoc B  0.00199203187250996
Test 2 L assoc A | B  0.13545816733067728
Test 3 A assoc B | L  0.00199203187250996
Test 4 L ind B | A  0.00199203187250996
Overlap score from Test 4  0.330563381197838
Seed set at  824259423708802955

[0.13545816733067728,
 0.00199203187250996,
 0.13545816733067728,
 0.00199203187250996,
 0.00199203187250996,
 0.330563381197838,
 824259423708802955]

In [22]:
nlcd_single(L,A,B,shuffles=500,algo='KRR',sample_seed=824259423708802955)

The final p value is  0.13545816733067728
Test 1 L assoc B  0.00199203187250996
Test 2 L assoc A | B  0.13545816733067728
Test 3 A assoc B | L  0.00199203187250996
Test 4 L ind B | A  0.00199203187250996
Overlap score from Test 4  0.330563381197838
Seed set at  824259423708802955

[0.13545816733067728,
 0.00199203187250996,
 0.13545816733067728,
 0.00199203187250996,
 0.00199203187250996,
 0.330563381197838,
 824259423708802955]

In [8]:
import numpy as np

def generate_pleiotropy_triplet(n, b_LA, b_LB, b_AB, seed):
    """
    Pleiotropy DGP:
        L ~ Bernoulli(0.5)
        A = b_LA * L + N(0, 1)
        B = b_LB * L + b_AB * A + N(0, 1)

    L -> A (causal), A -> B (causal, strength b_AB),
    L -> B (pleiotropic direct effect, strength b_LB).

    Seeded with np.random.default_rng for full reproducibility.
    """
    rng = np.random.default_rng(seed)
    L = rng.binomial(1, 0.5, n)
    A = b_LA * L + rng.normal(0, 1, n)
    B = b_LB * L + b_AB * A + rng.normal(0, 1, n)
    return L, A, B

In [11]:

# ---- Run NLCD on the two scenarios ---------------------------------
N    = 500       # sample size
SEED = 42        # fixed for reproducibility — same L, A across both runs

# Triplet 1: beta_AB = 1  (moderate A -> B coupling, comparable to pleiotropy)
L1, A1, B1 = generate_pleiotropy_triplet(N, b_LA=1, b_LB=1, b_AB=1,  seed=SEED)

# Triplet 2: beta_AB = 10 (strong A -> B coupling, dominates pleiotropy)
L2, A2, B2 = generate_pleiotropy_triplet(N, b_LA=1, b_LB=1, b_AB=10, seed=SEED)

L3, A3, B3 = generate_pleiotropy_triplet(N, b_LA=1, b_LB=1, b_AB=100, seed=SEED)

In [13]:


print('=' * 60)
print('Triplet 1: b_LA=1, b_LB=1, b_AB=1   (pleiotropy comparable to causal A->B)')
print('=' * 60)
res1 = nlcd_single(L1, A1, B1, shuffles=500, algo='KRR', verbose=True)

print('\n' + '=' * 60)
print('Triplet 2: b_LA=1, b_LB=1, b_AB=10  (causal A->B dominates pleiotropy)')
print('=' * 60)
res2 = nlcd_single(L2, A2, B2, shuffles=500, algo='KRR', verbose=True)

print('\n' + '=' * 60)
print('Triplet 3: b_LA=1, b_LB=1, b_AB=100 (causal A->B dominates pleiotropy)')
print('=' * 60)
res2 = nlcd_single(L3, A3, B3, shuffles=500, algo='KRR', verbose=True)

============================================================
Triplet 1: b_LA=1, b_LB=1, b_AB=1   (pleiotropy comparable to causal A->B)
============================================================
The final p value is  0.8844621513944223
Test 1 L assoc B  0.00199203187250996
Test 2 L assoc A | B  0.8844621513944223
Test 3 A assoc B | L  0.00199203187250996
Test 4 L ind B | A  0.00199203187250996
Overlap score from Test 4  0.32939520378721426
Seed set at  896199062445547456

============================================================
Triplet 2: b_LA=1, b_LB=1, b_AB=10  (causal A->B dominates pleiotropy)
============================================================
The final p value is  0.5597609561752988
Test 1 L assoc B  0.00199203187250996
Test 2 L assoc A | B  0.5597609561752988
Test 3 A assoc B | L  0.00199203187250996
Test 4 L ind B | A  0.00199203187250996
Overlap score from Test 4  0.32939520378721426
Seed set at  397230322956127459

============================================================
Triplet 3: b_LA=1, b_LB=1, b_AB=100 (causal A->B dominates pleiotropy)
============================================================
The final p value is  0.00199203187250996
Test 1 L assoc B  0.00199203187250996
Test 2 L assoc A | B  0.00199203187250996
Test 3 A assoc B | L  0.00199203187250996
Test 4 L ind B | A  0.00199203187250996
Overlap score from Test 4  0.32939520378721426
Seed set at  1068022135021870695

## OVERFIT COMMENT

### original data

In [4]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i  ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_original.txt -s 500 --seed 42

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  no-split
start time:  1779628318.6364555  end time:  1779628361.1010485 Execution time: 42.464592933654785 seconds

original data 1000 samples

In [1]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i  ./data/Sine1000.txt -o ./figures/rebuttal/sine1000KRR_original.txt -s 500 --seed 42

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  1000  reverse  False  mode  no-split
start time:  1779752546.6538777  end time:  1779752892.473568 Execution time: 345.81969022750854 seconds

### original independent

In [1]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i  ./data/Indp500.txt -o ./figures/rebuttal/Indp500KRR_original.txt -s 500 --seed 42

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  no-split
start time:  1779803825.226704  end time:  1779803868.310049 Execution time: 43.08334517478943 seconds

### split data

In [5]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_split.txt  -s 500 --seed 42 --split --train-frac 0.8

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  split (train_frac=0.8)
start time:  1779628367.0097978  end time:  1779628404.205841 Execution time: 37.196043252944946 seconds

### split data train fac 0.5

In [2]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_split_0.5.txt  -s 500 --seed 42 --split --train-frac 0.5

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  split (train_frac=0.5)
start time:  1779722480.9108996  end time:  1779722500.9614816 Execution time: 20.05058193206787 seconds

### split data train fac 0.6

In [5]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_split_0.6.txt  -s 500 --seed 42 --split --train-frac 0.6

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  split (train_frac=0.6)
start time:  1779722664.641395  end time:  1779722690.3256972 Execution time: 25.68430209159851 seconds

### split data train fac 0.7

In [ ]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_split_0.7.txt  -s 500 --seed 42 --split --train-frac 0.7

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  split (train_frac=0.7)
start time:  1779722619.4489791  end time:  1779722651.089341 Execution time: 31.640361785888672 seconds

! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine500.txt -o ./figures/rebuttal/sine500KRR_split_0.6.txt  -s 500 --seed 42 --split --train-frac 0.6

### split independent

In [2]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Indp500.txt -o ./figures/rebuttal/Indp500KRR_split_0.8.txt  -s 500 --seed 42 --split --train-frac 0.8

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  500  reverse  False  mode  split (train_frac=0.8)
start time:  1779803884.299287  end time:  1779803921.9269798 Execution time: 37.62769269943237 seconds

### split 1000 samples

In [2]:
! python3 ./scripts/nlcd_simulation.py -a KRR -i ./data/Sine1000.txt -o ./figures/rebuttal/sine1000KRR_split.txt  -s 500 --seed 42 --split --train-frac 0.8

Seed Set at  42
Algo  KRR  shuffles  500  datasize =  1000  reverse  False  mode  split (train_frac=0.8)
start time:  1779752893.5420554  end time:  1779753161.1343093 Execution time: 267.59225392341614 seconds